### ISSUE TITLE
SSSpigot cannot load plugin.yml with libraries correctly

### ISSUE THREAD

**Issue by mrstirlic** [foss-mc/SSSpigot#8]
**Observed behavior on SSSpigot**
Good afternoon, I inform you about one bug (more precisely, this is a serious error), which I recently in SSSpigot, the core of SSSpigot cannot cope with loading plugin.yml with libraries (this is present in some plugins)

**Installed plugins**
PunishControl and 2fa

**Version**
SSSpigot version SSSpigot2-1.17.1-20210720-42a0458 (MC: 1.17.1)

**Error Log**
[20:20:16 ERROR]: Could not load 'plugins\2fa-1.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:299) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:122) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:511) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        ... 7 more
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.libs.org.apache.http.client.utils.URIUtils$UriFlag not an enum
        at java.util.EnumSet.noneOf(EnumSet.java:113) ~[?:?]
        at org.bukkit.craftbukkit.libs.org.apache.http.client.utils.URIUtils.<clinit>(URIUtils.java:66) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:122) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:71) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:104) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:129) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:155) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:107) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:511) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[ssspigot215242549212931162718.jar:SSSpigot2-1.17.1-20210720-42a0458]
        ... 7 more

**Example plugin.yml**
name: 2FA
version: "1.4.1"
authors: [LielAmar]
main: com.lielamar.auth.bukkit.TwoFactorAuthentication
api-version: 1.13
description: Add another layer of protection to your server

libraries:
  - com.warrenstrange:googleauth:1.4.0
  - commons-codec:commons-codec:1.6
  - com.zaxxer:HikariCP:4.0.3
  - com.h2database:h2:1.4.200
  - org.mariadb.jdbc:mariadb-java-client:3.0.0-alpha
  - org.postgresql:postgresql:42.2.23
  - org.mongodb:mongo-java-driver:3.12.7

commands:
  2fa:
    description: Main 2FA Command
    aliases: [auth]

permissions:
  2fa.*:
    description: Permissions to all 2FA commands
    default: op
    children:
      2fa.use: true
      2fa.help: true
      2fa.remove: true
      2fa.remove.others: true
      2fa.reload: true
  2fa.use:
    description: Permissions to use the /2FA command
    default: op
  2fa.help:
    description: Permissions to view the help page
    default: op
  2fa.remove:
    description: Permissions to remove your own 2FA
    default: op
  2fa.remove.others:
    description: Admin permissions to remove other players' 2FA
    default: op
  2fa.reload:
    description: Admin permissions to reload the 2FA plugin
    default: op
  2fa.demand:
    description: A player with this permission must have 2FA linked to thier account
    default: false

**Comment by foss-mc** [comment]
fixed
