### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Erelima** [foss-mc/SSSpigot#9]
**Installed plugins**
```
 AntiCheatReload*, AntiSeedCracker, ArmoredElytra, AsyncWorldEdit*, CoreProtect, CoreProtectTNT, CraftEnhance, DiscordSRV, dynmap, Essentials, EssentialsSpawn, F3Name, FarmLimiter, Geyser-Spigot, GiveMeArms, GSit, HiveChecker, IllegalStack, InventorySaver, LimitPillagers, LiteBans, Matrix, MiniMOTD, MySpeedProtection*, NitroCommandBlocker*, NoBedExplosions, NoLagg*, PlasmoVoice, PosePlugin*, ProtocolLib, ResourcePackDownloader*, ReUtils*, RW-Vanilla, SkinsRestorer, SuperVanish, WorldBorder
```

**Version**
```
 This server is running SSSpigot version SSSpigot2-1.17.1-20210722-551a891 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
 ```

**Crash**:
```
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1693) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:502) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?]
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189) ~[?:?]
	at java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2002) ~[?:?]
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:763) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:276) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processChunkUnload(PersistentEntitySectionManager.java:304) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processUnloads$10(PersistentEntitySectionManager.java:322) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at it.unimi.dsi.fastutil.longs.LongCollection.removeIf(LongCollection.java:197) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processUnloads(PersistentEntitySectionManager.java:321) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.tick(PersistentEntitySectionManager.java:345) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:842) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1673) ~[ssspigot25369425619555841165.jar:SSSpigot2-1.17.1-20210722-551a891]
	... 5 more```

**Comment by foss-mc** [comment]
fixed
